In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [6]:
def initalize_parameters(layer_dims):
    np.random.seed(4)
    parameters={}
    L=len(layer_dims)

    for l in range(1,L):
        parameters['W'+str(l)]=np.ones((layer_dims[l-1],layer_dims[l]))*0.1
        parameters['b'+str(l)]=np.zeros((layer_dims[l],1))
    return parameters

In [7]:
initalize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [8]:
def linear_forward(A_prev,W,b):
    Z = np.dot(W.T,A_prev)+b

    return Z
    

In [64]:
def L_layer_forward(X,parameters):
    A=X
    L=len(parameters) //2   # Number of parameters

    for l in range(1,L+1):
        A_prev=A
        W1=parameters['W'+str(l)]
        b1=parameters['b'+str(l)]
        # print('A'+str(l-1)+': ',A_prev)
        # print('W'+str(l)+': ',W1)
        # print('b'+str(l)+': ',b1)

        # print('--'*20)

        A=linear_forward(A_prev,W1,b1)
        # print('A'+str(l)+': ',A)
        # print('**'*20)

    return A,A_prev

In [27]:
X=df[['cgpa','profile_score']].values[0].reshape(2,1) # Shape(no. of features, no. of training samples)
y=df[['lpa']].values[0][0]

parameters=initalize_parameters([2,2,1])

In [33]:
y_hat,A1 = L_layer_forward(X,parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [35]:
y_hat=y_hat[0][0]

0.32000000000000006

In [36]:
A1


array([[1.6],
       [1.6]])

In [29]:
(y-0.32)**2

13.5424

In [41]:
update_parameters(parameters,y,y_hat,A1,X)

In [40]:
def update_parameters(parameters,y,y_hat,A1,X):
    # Update parameters using the formula written in Tab notes
    parameters['W2'][0][0]=parameters['W2'][0][0]+(0.001*2*(y-y_hat)*A1[0][0])
    parameters['W2'][1][0]=parameters['W2'][1][0]+(0.001*2*(y-y_hat)*A1[1][0])
    parameters['b2'][0][0]=parameters['W2'][1][0]+(0.001*2*(y-y_hat))

    parameters['W1'][0][0]=parameters['W1'][0][0]+(0.001*2*(y-y_hat)*parameters['W2'][0][0]*X[0][0])
    parameters['W1'][0][1]=parameters['W1'][0][1]+(0.001*2*(y-y_hat)*parameters['W2'][0][0]*X[1][0])
    parameters['b1'][0][0]=parameters['b1'][0][0]+(0.001*2*(y-y_hat)*parameters['W2'][0][0])

    parameters['W1'][1][0]=parameters['W1'][1][0]+(0.001*2*(y-y_hat)*parameters['W2'][1][0]*X[0][0])
    parameters['W1'][1][1]=parameters['W1'][1][1]+(0.001*2*(y-y_hat)*parameters['W2'][1][0]*X[1][0])
    parameters['b1'][1][0]=parameters['b1'][1][0]+(0.001*2*(y-y_hat)*parameters['W2'][1][0])

In [42]:
parameters

{'W1': array([[0.10700971, 0.10700971],
        [0.10796811, 0.10796811]]),
 'b1': array([[0.00087621],
        [0.00099601]]),
 'W2': array([[0.11905074],
        [0.135328  ]]),
 'b2': array([[0.142688]])}

In [43]:
# 2nd student

X=df[['cgpa','profile_score']].values[0].reshape(2,1) # Shape(no. of features, no. of training samples)
y=df[['lpa']].values[0][0]

y_hat,A1 = L_layer_forward(X,parameters)

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0:  [[8]
 [8]]
W1:  [[0.10700971 0.10700971]
 [0.10796811 0.10796811]]
b1:  [[0.00087621]
 [0.00099601]]
----------------------------------------
A1:  [[1.72069878]
 [1.72081858]]
****************************************
A1:  [[1.72069878]
 [1.72081858]]
W2:  [[0.11905074]
 [0.135328  ]]
b2:  [[0.142688]]
----------------------------------------
A2:  [[0.5804134]]
****************************************


In [52]:
# 3rd student

X=df[['cgpa','profile_score']].values[0].reshape(2,1) # Shape(no. of features, no. of training samples)
y=df[['lpa']].values[0][0]

y_hat,A1 = L_layer_forward(X,parameters)

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0:  [[8]
 [8]]
W1:  [[0.12987418 0.12987418]
 [0.13343484 0.13343484]]
b1:  [[0.00373427]
 [0.00417935]]
----------------------------------------
A1:  [[2.11020643]
 [2.11065151]]
****************************************
A1:  [[2.11020643]
 [2.11065151]]
W2:  [[0.15588366]
 [0.17216547]]
b2:  [[0.17863943]]
----------------------------------------
A2:  [[0.87096744]]
****************************************


{'W1': array([[0.13833957, 0.13833957],
        [0.1427155 , 0.1427155 ]]),
 'b1': array([[0.00479245],
        [0.00533944]]),
 'W2': array([[0.16908946],
        [0.18537407]]),
 'b2': array([[0.19163213]])}

In [49]:
# 4th student

X=df[['cgpa','profile_score']].values[0].reshape(2,1) # Shape(no. of features, no. of training samples)
y=df[['lpa']].values[0][0]

y_hat,A1 = L_layer_forward(X,parameters)

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0:  [[8]
 [8]]
W1:  [[0.12180071 0.12180071]
 [0.1245181  0.1245181 ]]
b1:  [[0.00272509]
 [0.00306476]]
----------------------------------------
A1:  [[1.97327553]
 [1.9736152 ]]
****************************************
A1:  [[1.97327553]
 [1.9736152 ]]
W2:  [[0.14310875]
 [0.15938837]]
b2:  [[0.1660559]]
----------------------------------------
A2:  [[0.7630202]]
****************************************


In [67]:
# All program in single cell

parameters = initalize_parameters([2,2,1])
epochs=1

for i in range(epochs):
    Loss=[]
    for j in range(df.shape[0]):
        X=df[['cgpa','profile_score']].values[j].reshape(2,1)
        y=df[['lpa']].values[j][0]

        y_hat,A1 = L_layer_forward(X,parameters)
        y_hat=y_hat[0][0]

        update_parameters(parameters,y,y_hat,A1,X)

        Loss.append((y-y_hat)**2)
        
    print('Epoch - ',i+1,' && Loss - ',np.array(Loss).mean())

parameters

Epoch -  1  && Loss -  25.321744156025517


{'W1': array([[0.13482804, 0.15847776],
        [0.1349909 , 0.15884991]]),
 'b1': array([[0.00569748],
        [0.0057292 ]]),
 'W2': array([[0.17312488],
        [0.17534027]]),
 'b2': array([[0.18773702]])}

In [68]:
## Same code in Keras

In [69]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [70]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [72]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [79]:
model=Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [80]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [83]:
model.compile(loss='mean_squared_error',optimizer='Adam')

In [81]:
model.get_weights()

[array([[-0.59167886,  0.47079182],
        [-0.28816593, -0.41136736]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.01389098],
        [-0.30618203]], dtype=float32),
 array([0.], dtype=float32)]

In [82]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)

In [86]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Train on 4 samples
Epoch 1/75
4/4 [==============================] - 0s 2ms/sample - loss: 0.2881
Epoch 2/75
4/4 [==============================] - 0s 2ms/sample - loss: 0.2839
Epoch 3/75
4/4 [==============================] - 0s 2ms/sample - loss: 0.2835
Epoch 4/75
4/4 [==============================] - 0s 2ms/sample - loss: 0.2813
Epoch 5/75
4/4 [==============================] - 0s 3ms/sample - loss: 0.2826
Epoch 6/75
4/4 [==============================] - 0s 2ms/sample - loss: 0.2788
Epoch 7/75
4/4 [==============================] - 0s 2ms/sample - loss: 0.2789
Epoch 8/75
4/4 [==============================] - 0s 2ms/sample - loss: 0.2774
Epoch 9/75
4/4 [==============================] - 0s 1ms/sample - loss: 0.2763
Epoch 10/75
4/4 [==============================] - 0s 2ms/sample - loss: 0.2757
Epoch 11/75
4/4 [==============================] - 0s 2ms/sample - loss: 0.2743
Epoch 12/75
4/4 [==============================] - 0s 2ms/sample - loss: 0.2739
Epoch 13/75
4/4 [=============

In [87]:
model.get_weights()

[array([[-0.86265904,  0.27658617],
        [-0.60956866, -0.6398368 ]], dtype=float32),
 array([-0.30418247, -0.21677722], dtype=float32),
 array([[-0.23220207],
        [-0.55324256]], dtype=float32),
 array([0.19012988], dtype=float32)]